config/routes.rb
Rails.application.routes.draw do
  root 'splash#splash'

  devise_scope :user do
    get "/users/sign_out", to: "devise/sessions#destroy"
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :categories, only: [:index, :new, :create] do
    resources :records, only: [:index, :new, :create]
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities based on the user role
    if user.admin?
      can :manage, :all
    else
      can :read, Record
      can :create, Record, user_id: user.id
      can :update, Record, user_id: user.id
      can :destroy, Record, user_id: user.id
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :records

  validates :name, presence: true, uniqueness: true
end

app/models/record.rb
class Record < ApplicationRecord
  has_and_belongs_to_many :categories
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'

  validates :name, presence: true
  validates :author_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :records, foreign_key: 'author_id'

  validates :name, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, :configure_permitted_parameters, if: :devise_controller?
  before_action :current_user

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  def after_sign_in_path_for(_resource)
    categories_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to categories_path, notice: 'Category created successfully.'
    else
      render :new
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :authenticate_user!

  def index
    @category = Category.find(params[:category_id])
    @records = @category.records.order(created_at: :desc)
    @total_amount = @category.records.sum(:amount)
  end

  def new
    @category = Category.find(params[:category_id])
    @record = @category.records.build
  end

  def create
    @category = Category.find(params[:category_id])
    @record = @category.records.build(record_params)
    @record.author = current_user

    if params[:record][:category_ids].present?
      @record.category_ids = params[:record][:category_ids]
    else
      @record.errors.add(:category_ids, 'must be selected')
    end

    if @record.save
      redirect_to category_records_path(@category), notice: 'Record created successfully.'
    else
      render :new
    end
  end

  private

  def record_params
    params.require(:record).permit(:name, :amount, :category_id, category_ids: [])
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  def splash; end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  protected

  def after_sign_up_path_for(_resource)
    root_path # Replace "splash_path" with the path to your splash page
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/views/categories/index.html.erb
<div class="navbar">
  <label for="navbar-toggle" class="navbar-toggle-label">
    <span></span>
    <span></span>
    <span></span>
  </label>
  <div class="navbar-brand category-title">
    <h1>Categories</h1>
  </div>
    <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "btn btn-primary" %>
</div>

<main>
  <% @categories.each do |category| %>
    <div class="category-record-card">
      <div class="category-record-info">
        <img src="<%= category.icon %>" alt="Category Icon" class="category-icon">
        <div class="category-details">
          <h2><%= category.name %></h2>
          <p class="amount">Total Amount: <%= number_to_currency(category.records.sum(:amount)) %></p>
        </div>
      </div>
      <div class="view-transactions">
        <%= link_to 'View Transactions', category_records_path(category), class: 'btn btn-primary' %>
      </div>
    </div>
<% end %>
<%= link_to "Add a New Category", new_category_path, class: "btn btn-primary add-transaction" %>
</main>

app/views/categories/new.html.erb
<div class="form-container">
  <div class="navbar">
    <h1 class="navbar-brand">New Category</h1>
    <%= link_to categories_path, class: "navbar-right" do %>
  <i class="fas fa-arrow-left"></i>
  <span class="sr-only">Back</span>
<% end %>

  </div>

  <%= form_for @category, html: { class: "navbar-form" } do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :icon %>
    <%= f.text_field :icon %>
    <%= f.submit "Save", class: "btn btn-primary" %>
  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/records/index.html.erb
<div class="navbar">
  <label for="navbar-toggle" class="navbar-toggle-label">
    <span></span>
    <span></span>
    <span></span>
  </label>
  <h1 class="navbar-brand record-title">Transactions for <%= @category.name %></h1>
 <%= link_to categories_path, class: "navbar-right" do %>
    <i class="fas fa-arrow-left"></i>
    <span class="sr-only">Back</span>
  <% end %>
</div>

<main>
  <p>Total Amount: <%= number_to_currency(@total_amount) %></p>

  <ul class="record-list">
    <% @records.each do |record| %>
      <li>
        <div class="record-card">
          <div class="record-info">
            <p><%= record.name %></p>
            <p class="amount"><%= number_to_currency(record.amount) %></p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>

  <%= link_to "Add a new transaction", new_category_record_path(@category), class: "btn btn-primary add-transaction" %>
</main>

app/views/records/new.html.erb
<div class="navbar">
  <h1 class="navbar-brand">New Transaction</h1>
  <%= link_to category_records_path(@category), class: "navbar-right" do %>
  <i class="fas fa-arrow-left"></i>
  <span class="sr-only">Back</span>
<% end %>

</div>

<div class="form-container">
  <h1>New Transaction</h1>

<%= form_for [@category, @record], html: { class: "navbar-form" } do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :amount %>
  <%= f.number_field :amount %>
  <%= f.label :categories %>
  <%= f.select :category_ids, Category.all.map { |category| [category.name, category.id] }, { include_blank: true }, { multiple: true } %>
  <%= f.submit "Create Transaction", class: "btn btn-primary" %>
<% end %>
  <% if @record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@record.errors.count, "error") %> prohibited this record from being saved:</h2>
      <ul>
        <% @record.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

app/views/splash/splash.html.erb
<div class="splash-container">
  <div class="splash-content">
    <h1 class="splash-brand">Welcome to Your Budget Management App</h1>
    <p class="splash-brand2">Track and manage your budget with ease.</p>
  </div>
  <div class="splash-buttons">
    <%= link_to 'Sign up', new_user_registration_path, class: 'splash-button1' %>
    <%= link_to 'Log in', new_user_session_path(redirect_to: categories_path), class: 'splash-button2' %>
  </div>
</div>